### PR TITLE
Jams giver1

### PR DESCRIPTION
**Pull request by joras-droid**

### CODE REVIEW

**Review by joras-droid — COMMENTED** [review]
done

**Comment by giver-kdk** [comment]
Verified

**Review by giver-kdk — APPROVED** [review]
ok

**Review by giver-kdk — APPROVED** [review]
ok

**Comment by giver-kdk** [comment]
Okay

**Comment by giver-kdk** [comment]
Retry

**Comment by giver-kdk** [comment]
Okay

**Pull request merged**
